baseURL = ""
title = "Dan Crowther"

theme = "hugo-theme-puppet-master"


copyright = ""
#paginate = 3
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = ""

[outputs]
home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html 
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 20
[[menu.main]]
identifier = "videos"
name = "My Portfolio"
url = "/series/video/"
#url = "/videos/"
weight = 10
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50
#[[menu.main]]
#identifier = "infra"
#name = "infra"
#url = "/series/infra/"
#weight = 100


[params]
author = "Dan"
description = "My Portfolio"
keywords = "blog,developer,personal"
#img_home = "img/home-bg.jpg"
#img_home = "https://source.unsplash.com/O2-EZNGZIyk"
img_home = "img/image_screens.avif"

img_404 = "img/404-bg.jpg"

useFaviconGenerator = false

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
enable = true
#avatar = "https://source.unsplash.com/ZdOsQiwp0Ss"
avatar = "/img/image_behind.avif"
bio = "My name is Dan Crowther - I play basketball and I record and edit videos"

[params.social]
#rss_enable = true
twitter = "dancrowther"
facebook = "dancrowther"
#zhihu = "johndoe"
#weibo = "dancrowther"
#github = "dancrowther"
linkedin = "dancrowther"
instagram = "mdbasketball1"
email = "dan@thecrowtherfamily.com"
youtube = "@mdbasketball"

[[params.friends]]
#name = "John Doe"
#url = "https://gohugo.io"

[[params.friends]]
#name = "John Doe"
#url = "https://gohugo.io"

# See https://giscus.app/
[params.giscus]
enable = false
repo = "roninro/hugo-theme-puppet"
repo_id = "R_kgDOHuvyhw"
category = "General"
category_id = "DIC_kwDOHuvyh84CQjDo"
input_position = "top"
theme = "light_tritanopia"
lang = "en"
